services:
  - type: web
    name: proposal-backend
    env: python
    plan: starter
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    autoDeploy: true
    disk:
      name: litefs-data
      mountPath: /litefs
      sizeGB: 1
    envVars:
      - key: DB_PATH
        value: /litefs/proposal_system.db
      - key: PORT
        value: 8000

  - type: web
    name: proposal-frontend
    env: node
    plan: starter
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NEXT_PUBLIC_API_URL
        fromService:
          name: proposal-backend
          type: web
